# Generated by Django 5.1.3 on 2024-11-06 05:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sentdex", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "card_number",
                    models.CharField(
                        max_length=16,
                        primary_key=True,
                        serialize=False,
                        verbose_name="شماره کارت",
                    ),
                ),
                (
                    "expiry_month",
                    models.CharField(max_length=2, verbose_name="ماه انقضا"),
                ),
                (
                    "expiry_year",
                    models.CharField(max_length=2, verbose_name="سال انقضا"),
                ),
                ("cvv", models.CharField(max_length=3, verbose_name="CVV")),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="موجودی"
                    ),
                ),
                (
                    "email",
                    models.EmailField(default="yshabanei@gmail.com", max_length=50),
                ),
            ],
            options={
                "verbose_name": "کارت",
                "verbose_name_plural": "کارت\u200cها",
            },
        ),
        migrations.CreateModel(
            name="NetBanking",
            fields=[
                (
                    "username",
                    models.CharField(
                        max_length=16,
                        primary_key=True,
                        serialize=False,
                        verbose_name="نام کاربری",
                    ),
                ),
                ("password", models.CharField(max_length=14, verbose_name="رمز عبور")),
                ("bank", models.CharField(max_length=25, verbose_name="بانک")),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="تعادل"
                    ),
                ),
            ],
            options={
                "verbose_name": "نت بانکینگ",
                "verbose_name_plural": "نت بانکینگ",
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "transaction_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="شناسه تراکنش"
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=10, verbose_name="نام کاربری"),
                ),
                (
                    "trip_reference_id",
                    models.IntegerField(default=1, verbose_name="شناسه سفر"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="مقدار"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="Failed", max_length=15, verbose_name="وضعیت"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="روش پرداخت"
                    ),
                ),
                (
                    "date_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاریخ و زمان"
                    ),
                ),
            ],
            options={
                "verbose_name": "تراکنش",
                "verbose_name_plural": "تراکنش\u200cها",
            },
        ),
        migrations.RenameField(
            model_name="detaileddescription",
            old_name="desc",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="detaileddescription",
            old_name="dest_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="passengerdetail",
            old_name="trip_same_id",
            new_name="trip_reference_id",
        ),
        migrations.AlterField(
            model_name="destination",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="شناسه"
            ),
        ),
        migrations.AlterField(
            model_name="detaileddescription",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=20000, max_digits=10, verbose_name="قیمت"
            ),
        ),
        migrations.AlterField(
            model_name="passengerdetail",
            name="payment",
            field=models.DecimalField(
                decimal_places=2, default=50, max_digits=10, verbose_name="پرداخت"
            ),
        ),
    ]
