# Generated by Django 5.1.3 on 2024-11-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sentdex", "0002_card_netbanking_transaction_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="email",
            field=models.EmailField(
                default="yshabanei@gmail.com", max_length=50, verbose_name="ایمیل"
            ),
        ),
    ]
